//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmmedipol.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_OKUL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRM_OKUL()
        {
            this.CRM_OGRENCI = new HashSet<CRM_OGRENCI>();
        }
    
        public byte ID { get; set; }
        public string MEZUNLISE { get; set; }
        public Nullable<byte> BOLUM { get; set; }
        public string OGRENIMDURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRM_OGRENCI> CRM_OGRENCI { get; set; }
        public virtual CRM_BOLUM CRM_BOLUM { get; set; }
    }
}
