//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmmedipol.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_SINAVSONUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRM_SINAVSONUC()
        {
            this.CRM_OGRENCI = new HashSet<CRM_OGRENCI>();
        }
    
        public byte ID { get; set; }
        public Nullable<decimal> TYT_PUAN { get; set; }
        public Nullable<int> TYT_SIRALAMA { get; set; }
        public Nullable<decimal> AYT_SAY_P { get; set; }
        public Nullable<decimal> AYT_EA_P { get; set; }
        public Nullable<decimal> AYT_SOZ_P { get; set; }
        public Nullable<decimal> AYT_DIL_P { get; set; }
        public Nullable<long> AYT_SAY_S { get; set; }
        public Nullable<long> AYT_EA_S { get; set; }
        public Nullable<long> AYT_SOZ_S { get; set; }
        public Nullable<long> AYT_DIL_S { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRM_OGRENCI> CRM_OGRENCI { get; set; }
    }
}
