//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crmmedipol.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRMMEDIPOLEntities : DbContext
    {
        public CRMMEDIPOLEntities()
            : base("name=CRMMEDIPOLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CRM_ADMIN> CRM_ADMIN { get; set; }
        public virtual DbSet<CRM_SEHIR> CRM_SEHIR { get; set; }
        public virtual DbSet<CRM_OGRENCI> CRM_OGRENCI { get; set; }
        public virtual DbSet<CRM_SINAVSONUC> CRM_SINAVSONUC { get; set; }
        public virtual DbSet<CRM_OKUL> CRM_OKUL { get; set; }
        public virtual DbSet<CRM_ILETISIM> CRM_ILETISIM { get; set; }
        public virtual DbSet<CRM_BOLUM> CRM_BOLUM { get; set; }
    }
}
